### ISSUE TITLE
JDK 15 vs Android Studio

### ISSUE THREAD

**Issue by kkuehl** [redouane59/twittered#26] opened 2020-08-13 15:25 UTC
I am excited about the new twitter-client, but it unfortunately makes Android Studio unhappy.
Unsupported class file version: 56
https://developer.android.com/studio/write/java8-support#supported_features

Any plans to eventually support JDK 8?
Thanks!

**Comment by redouane59** [comment] 2020-08-13 18:00
Hi @kkuehl ! 
Thanks for your interest. Unfortunately the project is using some new features (came from Java 9 to Java 12) not present in java 8 so I could not downgrade it.
I really have poor Android skills but maybe [this](https://jakewharton.com/androids-java-9-10-11-and-12-support/) can help ?

**Comment by jkolobok** [comment] 2020-09-21 19:02
Unfortunately the project is unusable because of jdk 12. Who uses jdk 12 in a serious project?
The library should support at least jdk8 to become popular.

**Comment by jkolobok** [comment] 2020-09-22 00:06
Apparently compilation works with java8 without any problems (just need to change version in pom)

**Comment by jkolobok** [comment] 2020-09-22 01:28
ok. I was not quite right. Doesn't compile, but the changes were very simple. I'll create a pull request.

**Comment by hypr2771** [comment] 2020-09-22 08:09
> Unfortunately the project is unusable because of jdk 12. Who uses jdk 12 in a serious project?
> The library should support at least jdk8 to become popular.

Just saying, following JDK releases is _not_ a bad practice.
JDK are bringing many handy features over time, and jumping multiple major versions is _never_ easy (if you want to do it correctly).
Why do you think JDK8 should be used to build instead of most recent releases?

**Comment by jkolobok** [comment] 2020-09-22 18:10
> Just saying, following JDK releases is _not_ a bad practice.
Not a bad practice for what? 
https://www.jetbrains.com/lp/devecosystem-2020/java/
The majority of projects are still using jdk 8 or 11. JDK 9,10,12(!),13,14(!) Are not supported anymore.
I'd somehow understand support of jdk11+, but the only thing used from jdk 11 is List.of instead of old Arrays.asList and Optional.isEmpty instead of just !Optional.isPresent. Is it really so important? 
> JDK are bringing many handy features over time, and jumping multiple major versions is _never_ easy (if you want to do it correctly).
Which exactly features are so important and that are actually being used in the project?

> Why do you think JDK8 should be used to build instead of most recent releases?
The most obvious reason is that there are tons of projects still using jdk8 that would like to use/try the library, but unable to do so. If you want to make it compatible with jdk 9+ e.g to add modularization it's fine, but don't break compatibility with the most popular version of java. 
Obviously it's your project and you can do whatever you want, but having to create a fork with the same functionality is stupid

**Comment by hypr2771** [comment] 2020-09-23 04:46
> Not a bad practice for what?
> The majority of projects are still using jdk 8 or 11. JDK 9,10,12(!),13,14(!) Are not supported anymore.
> I'd somehow understand support of jdk11+, but the only thing used from jdk 11 is List.of instead of old Arrays.asList and Optional.isEmpty instead of just !Optional.isPresent. Is it really so important?

I _understand_ that many projects still uses JDK 8, but it _does not_ mean that it is a good practice.
How long will it take for those project to migrate to JDK 15 when it might become the next long term support version? Which regression might it bring (disordered `Set` for instance)?
By migrating, I mean stop using deprecated features to use the recommended ones, _not_ just changing the build and target versions.
This is always simpler to follow latest stable release or even leaving one release ahead, while this is _almost_ always a pain to jump multiple versions and _actually_ upgrading your code base.

> The most obvious reason is that there are tons of projects still using jdk8 that would like to use/try the library, but unable to do so. If you want to make it compatible with jdk 9+ e.g to add modularization it's fine, but don't break compatibility with the most popular version of java.
> Obviously it's your project and you can do whatever you want, but having to create a fork with the same functionality is stupid

This is indeed _true_.
I mostly wanted to react on the "Who uses jdk 12 in a serious project?" which triggered me :grin:.

> https://www.jetbrains.com/lp/devecosystem-2020/java/

Thanks for the metrics on the JDK usage. I feel this does not quite makes lot of sense to not upgrade to latest JDK version and I would be rather prudent on the usage of the "preferred" wording on this resource.
Each time I had people not willing to migrate was because they were too busy or afraid of the breaking changes, never because they did not wanted to; but this might be another debate :grin:.

**Comment by indianknight** [comment] 2020-09-23 08:01
@jkolobok Could you please help me to figure out how to compile this lib with jdk8, I am thinking of going a toolchain way but so far no luck. all other services in my project uses jdk8 only one service has dependency to this lib and that don't compile. 
On IDE I do some trick to work with it, any help would be apreciated.
I tried using jdk14 (as I do in IDE where it works) but maven compile fails.

**Comment by jkolobok** [comment] 2020-09-23 11:43
@indianknight https://github.com/redouane59/twittered/pull/77

**Comment by jkolobok** [comment] 2020-09-23 12:26
> I _understand_ that many projects still uses JDK 8, but it _does not_ mean that it is a good practice.

Why it is not? The version is LTS. What are the benefits of upgrading?

> How long will it take for those project to migrate to JDK 15 when it might become the next long term support version? Which regression might it bring (disordered `Set` for instance)?
Ask yourself how much money it will cost and how much business value it will give? My answer is 'a lot' and 'zero'.

There is a lot of potential issues. I've done a lot of upgrades and seen a lot of problems with modularization for example. 
Anyway in most of the cases you have to solve problems spending time and money on them receiving zero extra value. 
Java15 won't be next lts. Then next its is java17... so you'd have to do at least a couple of upgrades again spending money, receiving 0 value.

I've seen problems doing even minor upgrade within the same jdk version, problems switching between oracle->openjdk.. a lot of them. So after that I'm trying to be as much conservative with upgrades as possible. 

> By migrating, I mean stop using deprecated features to use the recommended ones, _not_ just changing the build and target versions.

Even if you stop using them what about the dependencies of your project? They'll break. Some of them may be  not supported anynmore, for others upgrade to the same version will be in progress and not yet ready. What if you have hundreds of dependencies? How much 1 upgrade every 6 month will cost? 

> This is always simpler to follow latest stable release or even leaving one release ahead, while this is _almost_ always a pain to jump multiple versions and _actually_ upgrading your code base.

Simpler for whom? For developers getting money for the work or for business having to pay extra money and receiving zero value for that?


> This is indeed _true_.
> I mostly wanted to react on the "Who uses jdk 12 in a serious project?" which triggered me 😁.
> 
> > https://www.jetbrains.com/lp/devecosystem-2020/java/
> 
> Thanks for the metrics on the JDK usage. I feel this does not quite makes lot of sense to not upgrade to latest JDK version and I would be rather prudent on the usage of the "preferred" wording on this resource.
> Each time I had people not willing to migrate was because they were too busy or afraid of the breaking changes, never because they did not wanted to; but this might be another debate 😁.

**Comment by PhantomYdn** [comment] 2020-12-23 19:41
I'm also looking for support Java8. Please advise when mentioned PR #77  can be applied?

**Comment by redouane59** [comment] 2020-12-23 20:57
> I'm also looking for support Java8. Please advise when mentioned PR #77 can be applied?

Hi ! If @jkolobok agrees, you can just build a branch from the last release (v1.15) and downgrade it to jdk8. Then you will be able to use it without forcing the whole project to be downgraded.

**Comment by jkolobok** [comment] 2020-12-23 21:05
@PhantomYdn forget about this library. It's not any usable and the maintainers are too young to understand this. In theory you can grab the code from my branch and build your own library... but better just stick with api v1 until someone created something usable.  

@redouane59 I don't care. This project is drawing dead.

**Comment by PhantomYdn** [comment] 2020-12-23 21:38
@jkolobok , I tend to agree with you, unfortunately. Read a couple of threads here and also can't understand why supporting a wider range of JDKs considered to be a weak position.

@redouane59 , I can't call it "downgrade":) Per PR there is no strong dependency on features from new JDKs: everything was here in JDK8 as well. Seems that this PR is really easy way to expand coverage of use cases for your library. Hope that you will reconsider merging one day.

**Comment by mmornati** [comment] 2020-12-24 11:26
In the end guys... Just reading what you are saying make me thinking that the reason many projects still using JDK8 is because of you. JDK8 is deprecated and not supported anymore. Serious projects still using the latest LTS or they will be not serious at all.... At least the dev on these such of projects are not serious.

I don't think we should answer with such comments ("mainteiner is too young") to a decision but juste make the arguments to bring to something usable.

In my opinion the library should be compatible with the latest LTS available and not only with the really latest JDK. It is a library and, as you are saying, this make the lib itself useless. Especially because changes are very little in any new version. 
Not sure why you are asking for JDK8. Is that a limitation for Android studio?

If not I guess @redouane59 a good decision would be to make it compatible with older version of Java (up to you the version, but I will limot of needed, to the 11). It is only related to some code syntax you use I guess. The more JDK version you support, the more the library will be largely usable and used.

Hope this help 😉

**Comment by jkolobok** [comment] 2020-12-24 11:42
`JDK8 is deprecated and not supported anymore.` 
You are absolutely wrong.

 Reality: https://www.oracle.com/java/technologies/java-se-support-roadmap.html
Even oracle is going to support it until 2030. And jdk 8 support ends BEFORE jdk 11.

The latest jdk8 release has happened a month ago. Previous - 2 months ago.   
https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot

'deprecated and not supported' by zoomers:)

**Comment by jkolobok** [comment] 2020-12-24 11:44
Not even mentioning that jdk8 is far more popular than 12-15 all together https://dash.adoptopenjdk.net/trends

**Comment by mmornati** [comment] 2020-12-24 12:07
> `JDK8 is deprecated and not supported anymore.` 
> You are absolutely wrong.
> 
>  Reality: https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> Even oracle is going to support it until 2030. And jdk 8 support ends BEFORE jdk 11.
> 
> The latest jdk8 release has happened a month ago. Previous - 2 months ago.   
> https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot
> 
> 'deprecated and not supported' by zoomers:)
> 
> 

Yes you are right. But you should check what the Extend Support is for Oracle 😉

Fo not understand why you are all against update... Don't you like being updated?? 😂😂

But on the base message I'm agree with you. A Java library should be compatible with as much version as possible to be really useful. Or @redouane59 you can think to create different version built against different Java versions. Several libs are doing this.

**Comment by mmornati** [comment] 2020-12-24 12:09
> Not even mentioning that jdk8 is far more popular than 12-15 all together https://dash.adoptopenjdk.net/trends

Actually the only version to consider for production (on new products) should be jdk11. If you start a new project on jdk8 that's for me far away from a good decision.

**Comment by jkolobok** [comment] 2020-12-24 12:22
> > Not even mentioning that jdk8 is far more popular than 12-15 all together https://dash.adoptopenjdk.net/trends
> 
> Actually the only version to consider for production (on new products) should be jdk11. If you start a new project on jdk8 that's for me far away from a good decision.
 
Kind of true, but not true. If this is the only third party library you are going to use then jdk11 is fine. Otherwise you have to consider all other libraries/platforms you are going to use and their requirements. 
The project I'm working on is not new. It is still using jdk8 and many other libraries it depends on work well only with jdk8. I don't want to upgrade them all and retest the whole project. It would cost too much. 
Only developers grain money for updates. Business spends money on it. This is the difference.

**Comment by mmornati** [comment] 2020-12-24 12:29
Yeah I'm agree. This is always a big problem of legacy project: what the effort we are ready to put in them and what is the side cost.
But unfortunately the number of libs not compatible will jdk8 will increase in the coming months and years... And sometime impossible to ask for backward compatibility. At a moment Jdk8 project will be impossible to maintain without this upgrade. What will be the effort at that time? The same than today or bigger?
That's the big problem we are facing everyday 😅

**Comment by jkolobok** [comment] 2020-12-24 12:50
`And sometime impossible to ask for backward compatibility.`
This project is not the case.
I don't know where are those 'time' when it's impossible. The difference between jdk8 and 11 is pretty much cosmetic. There is zero things that can be done in 11 that you could not do with 8.
 For me it took less that an hour to make a PR increases number of supported applications from 1% or less to 90%+.
At that time it was supporting only jdk12+ and now it's even worse supporting only jdk15+.

**Comment by mmornati** [comment] 2020-12-24 13:23
> `And sometime impossible to ask for backward compatibility.`
> This project is not the case.
> I don't know where are those 'time' when it's impossible. The difference between jdk8 and 11 is pretty much cosmetic. There is zero things that can be done in 11 that you could not do with 8.
>  For me it took less that an hour to make a PR increases number of supported applications from 1% or less to 90%+.
> At that time it was supporting only jdk12+ and now it's even worse supporting only jdk15+. 

The code yes. The best enhancement on the jdk is the Garbage Collector. In the new version is working better.

**Comment by PhantomYdn** [comment] 2020-12-24 19:40
It's some kind of strange conversation... For me it's obvious: if there are 2 libraries - one is supporting all JDKs starting from JDK-8 and up to the most up-to-date and another one supporting only from JDK15 and up: then the first one is much more usable. Just because it might be used by a **wider range of projects**.  In other words: the first one is much more advanced because it's not limiting you. Supporting of JDK8 is not a "old school" or something bad: it's real maturity and understanding of current projects needs.

**Comment by mmornati** [comment] 2020-12-25 18:40
I can understand @PhantomYdn what you are saying... But it is a decision of lib mainteners.
If you want to say "I just want to support since the latest LTS" it is your right. Then the users will decide if they really need the lib if they can upgrade their project JDK or not.
As I said JDK is not only a matter of code... That's the shitty and useless part. Each jdk upgrade is putting much more things inside that just new code paradigms.
We are facing this decision everyday and today I will never chose jdk8 anymore for my projects because that's too old jdk. Extended support for Oracle means for all licensing projects you have to pay much more money to Oracle... 

As I said, JDK15 it is probably a very bad decision today because very few projects are using it in production. But it is a decision of the mainteiner. I don't understngand why we are trying to force him changing the decision with such agressing messages.

**Comment by mmornati** [comment] 2020-12-25 18:50
@PhantomYdn the licenses is allowing forking and redistribute. So what about forking the lib and changing the part related to the JDK15, translating them to jdk8. I did not work to the code but it should easy. 😉

**Comment by redouane59** [comment] 2020-12-25 19:01
Hi, thanks to you all for your messages. What can be done is maybe to create a new branch from the latest code version, downgrade the project to jdk8, and upload it to maven central repository with a different project name ? Like `com.github.redouane59.twittered-jdk8`. What do you think ?

**Comment by PhantomYdn** [comment] 2020-12-25 19:15
@redouane59 , please get me right. Thank you so much for your work. I know, how it's difficult to keep everybody happy:) But I'm struggling to understand you view here... It's possible to make your library compatible with all JDKs starting from 8 and 15 including. Single codebase, single build and multiple supported JDKs. Why it's so important to keep those few things which are making library not backward compatible?

Yea - fork is possible and even PR #77 is there. So this option is always there... But we are here to consolidate and do not split our efforts:)

**Comment by redouane59** [comment] 2020-12-25 19:21
Just created https://github.com/redouane59/twittered/pull/108 (to avoid having to rebase everything and resolve all conflicts on #77 manually). I'm going to upload it to maven central repository tonight and you will give me feedback :)

**Comment by jkolobok** [comment] 2020-12-25 19:23
Are you going to maintain both branches? 
Waste of time.

**Comment by redouane59** [comment] 2020-12-25 19:26
> Are you going to maintain both branches?
> Waste of time.
I'll try, otherwise whoever will want to help will be welcome :)

**Comment by jkolobok** [comment] 2020-12-25 19:29
We are trying to help.. lol.
In theory you can set target level to 8 and source to something between 11 and 15. You won't be able to use new api, but you'll be able to use some new language features. Not good, but better than two branches.

**Comment by redouane59** [comment] 2020-12-25 19:39
> In theory you can set target level to 8 and source to something between 11 and 15. 
I'll try it on the next few days, don't know if it will work well, @hypr2771 was thinking it won't.

**Comment by mmornati** [comment] 2020-12-25 19:50
I can take a look to the code @redouane59. What do you use of new JDKs? Records? Matches? I think it should be possible to change of all them (losing in readability in my opinion... But that's a fact in the end. Need to chose between largely usage and support VS new patterns).

**Comment by redouane59** [comment] 2020-12-25 19:57
> I can take a look to the code @redouane59. What do you use of new JDKs? Records? Matches? I think it should be possible to change of all them (losing in readability in my opinion... But that's a fact in the end. Need to chose between largely usage and support VS new patterns).

Nothing critical, but more things like `isEmpty()` , `List.of()` . The PR #108 is already done.

**Comment by redouane59** [comment] 2021-01-03 18:15
@PhantomYdn did you try the jdk8 version ? Is it working fine for you ?

**Comment by PhantomYdn** [comment] 2021-01-03 19:54
@redouane59 , not yet. We are working on open source scheduled posting solution: https://github.com/OrienteerBAP/OPoster and considering your library for communicating with twitter.

**Comment by redouane59** [comment] 2021-01-03 21:25
> @redouane59 , not yet. We are working on open source scheduled posting solution: https://github.com/OrienteerBAP/OPoster and considering your library for communicating with twitter.

Ok waiting for your feedback about this version, if it is concluant we'll consider merging it to the master :)

**Comment by zdenda-online** [comment] 2021-01-03 22:56
From my point of view, JDK15+ is just too aggressive. I would go at least JDK11 (JDK8 good as well). It is not only because of projects are forced but also some runtimes are not yet able to work with this high JDK. For example, I would love to create a simple serverless Java function (e.g. [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-java.html)) that uses this client. Unfortunately, Lambda has only java8 or java11. This restriction makes it just unusable.

Btw thanks for this client ;) looks good so far. Wish you the best.

**Comment by redouane59** [comment] 2021-01-04 19:38
> From my point of view, JDK15+ is just too aggressive. I would go at least JDK11 (JDK8 good as well). It is not only because of projects are forced but also some runtimes are not yet able to work with this high JDK. 

Understood,  as far as users will validate the jdk8 released version, we will consider merging it to master :)

**Comment by redouane59** [comment] 2021-01-12 09:25
Hey guys,
Just realized that Android decided last month to provide support for Java 11 :) 
https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html

Nice blog article talking about it : https://www.mobileit.cz/Blog/Pages/android-java-release-train.aspx

**Comment by PhantomYdn** [comment] 2021-01-19 04:05
@redouane59 , just added support of scheduled posting to Twitter through your library in the commit: https://github.com/OrienteerBAP/OPoster/commit/8d7c0bb15b2ba299b815ec6c2b7eec1c6ab03978

But will really appreciate if support of images will be added to the library. Created separate issue for that #120 

P.S. For now OPoster use separate `jdk8` branch, but it will be really cool if your library will become universal and start support of JDK8+

**Comment by redouane59** [comment] 2021-01-19 20:26
Hi @PhantomYdn ,
Like I said on your issue, the endpoint was implemented last week :)
Don't you want to submit a PR for Scheduled posting ?
About version, it looks like even Android has finally decide to move to jdk11, will it be the case of your project too ?

**Comment by PhantomYdn** [comment] 2021-01-19 22:21
@redouane59 , I'm really sorry, but I don't understand where is the problem with JDK8 support:) Look, if you have 2 keys: one can open only one small door and another key can open 8 doors. Which key is better? Imho, libraries should keep the lowest JDK possible unless:

1) It's absolutely clear what features from newer JDK is needed for the core functionality,
2) Most of clients has already moved forward

So I can't understand what's a feature of JDK11+ is a must-have for the functionality. Can you please help?

But answering to your question: [OPoster](https://github.com/OrienteerBAP/OPoster) depended on [Orienteer](https://github.com/OrienteerBAP/Orienteer) which also depends on [OrientDB](https://github.com/orientechnologies/orientdb). And last one works on JDK8, but guys are also working on moving to JDK11. But you can imagine how many other software depends on them, and update from JDK8 is much more complex for them. And complex not due to code changes, but due to requirement to move the massive set of the customer to newer JDK as well.

**Comment by mmornati** [comment] 2021-01-20 12:31
Quite agree with what @PhantomYdn is saying. In the end, global libraries should be built to be used on a big number of projects. So it is better to build the lib with a lower JDK. This will allow someone with JDK11, 12,15 or 17 to use it. The opposite is not possible.

Is there any other things you really need forcing you to use a JDK againt one other?

**Comment by redouane59** [comment] 2021-01-20 12:56
> Is there any other things you really need forcing you to use a JDK againt one other?

Nothing critical just a little bit of refactoring already done in PR https://github.com/redouane59/twittered/pull/121 
I heard your arguments, I will merge the PR this week.

**Comment by redouane59** [comment] 2021-01-24 20:59
Solved in https://github.com/redouane59/twittered/pull/123

**Closed by redouane59** 2021-01-24 20:59 UTC
