### ISSUE TITLE
How to retrieve the avatar image url using the twitter client?

### ISSUE THREAD

**Issue by kopax** [redouane59/twittered#163] opened 2021-04-11 12:08 UTC
I want to display a tweet I have just posted, How to retrieve the avatar image url using the twitter client?

It seems it is possible in v1.1 but not implemented: https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-show

**Comment by redouane59** [comment] 2021-04-11 12:21
Hi @kopax ,

The V2 endpoint actually allow you to get this information too.
Example : 
``` 
    UserV2 user = twitterClient.getUserFromUserName("kopax");
    String imgUrl = user.getData().getProfileImageUrl();
```

**Comment by kopax** [comment] 2021-04-11 13:57
`twitterClient.getUserFromUserName()` does return :

```json
{
  "data": null,
  "includes": null
}
```

**Comment by redouane59** [comment] 2021-04-11 14:28
The problem is related with your twitter account, not with the library. Just check the log error message :)

**Comment by kopax** [comment] 2021-04-11 14:30
I've checked it and it seems this application can't enroll for the API program. I only have one token for it and it's from a different app.. It's not possible to use the API v2, can't we use the endpoint for v1 with some hacked code?

**Comment by redouane59** [comment] 2021-04-11 14:34
The enrollment should be free, I don't know why you cannot do it. You can always post a message in the twitter dev forum to have their help.
To have the twitter avatar URL, as explained before, you can just use : 
```
    UserV2 user = twitterClient.getUserFromUserName("kopax");
    String imgUrl = user.getData().getProfileImageUrl();
``` 
But this will work when you will have a twitter dev project within your account. See : https://developer.twitter.com/en/docs/projects/faq

**Comment by kopax** [comment] 2021-04-11 14:40
> > Can I have more than one App connected to a Project?
> At this time, you may only connect one App per Project. In the future we will introduce the capability to add more than one App per Project.

Vv1 is deprecated but it is at least available to every app. Is downgrading for me possible at this point?

**Comment by redouane59** [comment] 2021-04-11 14:50
Why can't you just create another project to link your 2nd app ?

For the V1 endpoint, you can check the [releases](https://github.com/redouane59/twittered/releases) but I'm absolutely not sure that avatar url was available in V1. The library evolved a lot so that's not a good idea to downgrade it.

The other solution would be to override this endpoint on your side and implement it in your project directly without using mine. But I'm sure that the best solution would be to make your twitter account work properly :)

**Comment by kopax** [comment] 2021-04-11 15:37
> Why can't you just create another project to link your 2nd app ?

You can have only one project that support API v2, the rest will support API v1.

I could create another TwitterAccount but then it's not convenient to use another account API key than the one we are posting for, it will require two twitter clients.

**Comment by redouane59** [comment] 2021-04-11 15:41
Hmm ok I didn't know. And why not using the same app and project ?

**Comment by kopax** [comment] 2021-04-11 15:46
It's two different app and it's forbidden by twitter rules:

> How many Projects can I create? 
> You are currently allowed to have one Standard Project and, if approved for access, one Academic Research Project. We may expand the number of Projects you can create as we launch more products and features.

**Comment by JessicaGarson** [comment] 2021-04-13 17:17
At this time, you can only create App per Project. You can only have one Project per product track. If you had academic access, you could have one Project for academic access and one for standard access. We are considering making changes here for the future. 

Only Apps connected to Projects can connect to v2. These Apps can also connect to v1.1 too. Standalone Apps can connect to v1.1 only. If you have an App connected to a Project, you should be able to connect directly to these new endpoints. You can also connect any of your existing Apps to a Project. 

Happy to help further. You can let us know if you have any further trouble on the [forums](twittercommunity.com).

**Comment by kopax-polyconseil** [comment] 2021-04-13 18:13
Hi @JessicaGarson and thanks for clarifying the différence between app and project.

![image](https://user-images.githubusercontent.com/77674046/114600364-8b3c2680-9c94-11eb-9e04-60f15374d6cb.png)


I think they are already attached, how do you generate a V2 token for the standalone application ?

I have created an issue on twitter community forum https://twittercommunity.com/t/how-to-attach-an-app-to-a-project/152637

**Comment by JessicaGarson** [comment] 2021-04-13 21:17
So `My Back-Office` would only have access to v1 but `My Public Website` could access both v1 and v2. You can get the keys and tokens you need inside the Keys and Tokens section of `My Public Website`. I think this tutorial may be helpful for you [here](https://dev.to/twitterdev/step-by-step-guide-to-making-your-first-request-to-the-new-twitter-api-v2-42mi). 

I saw you already engaging with someone else via the forums but I'll chime in there too.

**Comment by kopax-polyconseil** [comment] 2021-04-13 21:25
Just to make sure, are you suggesting to use the tokens from `My Public Website` for `My Back-Office` ? This is strictly forbidden by Twitter rules.

**Comment by redouane59** [comment] 2021-04-15 17:46
I'm closing the issue as you created someone in the [twitter forum](https://twittercommunity.com/t/how-to-attach-an-app-to-a-project/152637/2).

See you !

**Closed by redouane59** 2021-04-15 17:46 UTC

**Comment by kopax** [comment] 2021-04-15 17:55
@redouane59 answer on twitter forum was supporting the idea of restoring the v1 api....

**Comment by redouane59** [comment] 2021-04-15 18:59
> @redouane59 answer on twitter forum was supporting the idea of restoring the v1 api....

So you can just override the method and call the V1 endpoint instead of the V2 :)

**Comment by kopax-polyconseil** [comment] 2021-04-19 18:59
I've just tested that and `UserV1` doest not have all the fields such as `profile_image_url_https` missing.

Can I just extend `UserV1` , add those fields and class cast to get the value? It looks to be righter to directly add those things here, I am just being curious why aren't we doing that?

**Comment by redouane59** [comment] 2021-04-20 12:54
I saw that you removed your last message, is it ok ? Of course you can extend whatever you want :)

**Comment by kopax** [comment] 2021-04-20 12:56
Yes @redouane59 I did because extending did work great and I am now able to retrieve avatar of my twitter users. 

I still feel it's weird that this library is not supporting those endpoints, this forced me to duplicate multiple class, while it is twitter API v1 covered by this package. But still, thanks for doing this package :)

**Comment by RedouaneBALI** [comment] 2021-04-20 13:10
Yes I understand you, maybe the decision to delete the V1 endpoints once the V2 were released was a bad one and I had to keep the two versions on the library. 
@JessicaGarson what is your feeling about it, should libraries support V1 + V2 endpoints even if they exist on the two sides ?

**Comment by redouane59** [comment] 2021-04-20 13:10
Yes I understand you, maybe the decision to delete the V1 endpoints once the V2 were released was a bad one and I had to keep the two versions on the library.
@JessicaGarson what is your feeling about it, should libraries support V1 + V2 endpoints even if they exist on the two sides ?

**Comment by JessicaGarson** [comment] 2021-04-20 23:55
Thanks, @redouane59! At some point in the future, we may deprecate v1 endpoints, but at this point, it's up to the library maintainer. V2 endpoints do represent the direction we're heading for the future. We're here to help you out, and we appreciate the service and support you provide to the community.

**Comment by kopax-polyconseil** [comment] 2021-05-01 13:42
Hi @redouane59 ! I am just working with your module again and I am curious, will you take an action for the module at this point?  Every method I call must be from v1 endpoints and I have to rewrite almost all the methods on my end. Classes are missing to handle v1 response. Using v2 is still not an option until Twitter allows more than one application for v2 API.

**Comment by redouane59** [comment] 2021-05-01 15:20
Hi @kopax-polyconseil ,

Is it too hard for me to maintain V1+V2 endpoints. Each time a new V2 endpoint is released, I remove the old one and replace it with the new implementation. 
@JessicaGarson could you tell us when it will be possible to have several applications using v2 API ?
